/**
 * Playwright Test Suite Generator for MaviCore App Registry
 * ==============================================================================
 * Automatically generates production-grade @playwright/test specification files
 * from the machine-readable App Registry (/app-registry/{appId}/).
 *
 * Uses stable selectors: [data-mavi-id="..."] and [data-testid="..."]
 * ==============================================================================
 */

import { appRegistryService } from '../appRegistry/appRegistryService';

export const playwrightTestGenerator = {
  /**
   * Generates a complete, executable Playwright .spec.js script from registry data or project state
   */
  generateSpecCode(registryOrState = {}) {
    let registry = registryOrState;
    if (!registry['app.json'] && (registry.steps || registry.appName || registry.currentAppId)) {
      registry = appRegistryService.generateRegistry(registryOrState);
    }

    const appManifest = registry['app.json'] || {};
    const routes = registry['routes.json'] || [];
    const components = registry['components.json'] || [];
    const variables = registry['variables.json'] || [];
    const dataBindings = registry['data-bindings.json'] || [];
    const triggers = registry['triggers.json'] || [];
    const tools = registry['tools.json'] || [];
    const testContract = registry['test-contract.json'] || {};

    const appId = appManifest.appId || 'mavicore-app';
    const appName = appManifest.name || 'MaviCore Application';

    // Base URL path for HashRouter
    const baseHashRoute = `/#/builder`;

    const codeLines = [
      `// ==============================================================================`,
      `// AUTO-GENERATED PLAYWRIGHT TEST SUITE FOR: ${appName}`,
      `// App ID: ${appId} | Generated by MaviCore Auto App Registry Engine`,
      `// DO NOT EDIT MANUALLY — Automatically generated from /app-registry/${appId}/`,
      `// ==============================================================================`,
      ``,
      `import { test, expect } from '@playwright/test';`,
      ``,
      `test.describe('${appName} [App Registry Suite]', () => {`,
      `  test.beforeEach(async ({ page }) => {`,
      `    // Open AppBuilder canvas in isolated test environment`,
      `    await page.goto('${baseHashRoute}');`,
      `    await page.waitForLoadState('domcontentloaded');`,
      `    // Ensure canvas container is ready`,
      `    await expect(page.locator('.app-builder-canvas, [data-canvas-container="true"], #canvas-container').first()).toBeVisible({ timeout: 15000 });`,
      `  });`,
      ``,
      `  // --------------------------------------------------------------------------`,
      `  // 1. ROUTE & NAVIGATION TESTS`,
      `  // --------------------------------------------------------------------------`,
    ];

    routes.forEach((route, idx) => {
      const safeTitle = (route.title || `Screen ${idx + 1}`).replace(/"/g, '\\"');
      codeLines.push(
        `  test('Route Test: Screen "${safeTitle}" (${route.id})', async ({ page }) => {`,
        `    // Verify screen tab exists or can be navigated to`,
        `    const screenTab = page.locator(\`button:has-text("${safeTitle}")\`).or(page.locator('[data-testid="step-tab-${route.id}"]')).first();`,
        `    if (await screenTab.isVisible({ timeout: 2000 }).catch(() => false)) {`,
        `      await screenTab.click();`,
        `    }`,
        `    await page.waitForTimeout(300);`,
        `  });`,
        ``
      );
    });

    codeLines.push(
      `  // --------------------------------------------------------------------------`,
      `  // 2. COMPONENT PRESENCE & VISIBILITY TESTS`,
      `  // --------------------------------------------------------------------------`
    );

    components.slice(0, 20).forEach((comp) => {
      const selectorVal = comp.selector?.value || comp.instanceId;
      const originalId = comp.originalId || comp.instanceId;
      const safeDisplayName = (comp.displayName || comp.type).replace(/"/g, '\\"');
      codeLines.push(
        `  test('Component Test: "${safeDisplayName}" [${selectorVal}]', async ({ page }) => {`,
        `    const locator = page.locator('[data-mavi-id="${selectorVal}"]')`,
        `      .or(page.locator('[data-widget-id="${originalId}"]'))`,
        `      .or(page.locator('[data-testid="${selectorVal}"]')).first();`,
        `    await expect(locator).toBeAttached({ timeout: 5000 });`,
        comp.test?.visible
          ? `    await expect(locator).toBeVisible();`
          : `    // Component configured as background or initially hidden`,
        `  });`,
        ``
      );
    });

    codeLines.push(
      `  // --------------------------------------------------------------------------`,
      `  // 3. VARIABLE & DATA BINDING TESTS`,
      `  // --------------------------------------------------------------------------`
    );

    dataBindings.forEach((binding) => {
      codeLines.push(
        `  test('Data Binding Test: ${binding.component} ↔ ${binding.variable}', async ({ page }) => {`,
        `    const input = page.locator('[data-mavi-id="${binding.component}"] input, [data-mavi-id="${binding.component}"]');`,
        `    if (await input.isVisible()) {`,
        `      await input.fill('72');`,
        `      // Verify input retains value`,
        `      await expect(input).toHaveValue(/72/);`,
        `    }`,
        `  });`,
        ``
      );
    });

    codeLines.push(
      `  // --------------------------------------------------------------------------`,
      `  // 4. INTERACTION & TRIGGER TESTS`,
      `  // --------------------------------------------------------------------------`
    );

    const interactiveButtons = components.filter((c) => ['BUTTON', 'ACTION_BUTTON'].includes(c.type));
    interactiveButtons.forEach((btn) => {
      codeLines.push(
        `  test('Interaction Test: Click Button "${btn.displayName}" [${btn.selector.value}]', async ({ page }) => {`,
        `    const btnLocator = page.locator('[data-mavi-id="${btn.selector.value}"] button, [data-mavi-id="${btn.selector.value}"]');`,
        `    if (await btnLocator.isVisible()) {`,
        `      await btnLocator.click();`,
        `      await page.waitForTimeout(500);`,
        `    }`,
        `  });`,
        ``
      );
    });

    codeLines.push(
      `  // --------------------------------------------------------------------------`,
      `  // 5. NEGATIVE & BOUNDARY VALIDATION TESTS`,
      `  // --------------------------------------------------------------------------`
    );

    variables.filter((v) => v.type === 'number').slice(0, 3).forEach((v) => {
      const bound = dataBindings.find((b) => b.variable === v.id);
      if (bound) {
        codeLines.push(
          `  test('Negative Validation: Out of Range on ${bound.component}', async ({ page }) => {`,
          `    const input = page.locator('[data-mavi-id="${bound.component}"] input, [data-mavi-id="${bound.component}"]');`,
          `    if (await input.isVisible()) {`,
          `      await input.fill('-999');`,
          `      await input.blur();`,
          `      // Assert system does not crash and boundary validation handles invalid values`,
          `      await expect(page.locator('body')).not.toContainText('Uncaught TypeError');`,
          `    }`,
          `  });`,
          ``
        );
      }
    });

    codeLines.push(
      `  // --------------------------------------------------------------------------`,
      `  // 6. COMPLETE END-TO-END WORKFLOW TEST`,
      `  // --------------------------------------------------------------------------`,
      `  test('E2E Flow: Full Execution Scenario for ${appName}', async ({ page }) => {`,
      `    // 1. Initial screen load`,
      `    await expect(page.locator('.app-builder-canvas, [data-canvas-container="true"]').first()).toBeVisible();`,
      ``,
      `    // 2. Fill available input fields`,
      `    const inputs = page.locator('[data-mavi-id] input');`,
      `    const count = await inputs.count();`,
      `    for (let i = 0; i < Math.min(count, 4); i++) {`,
      `      const inp = inputs.nth(i);`,
      `      if (await inp.isVisible()) {`,
      `        await inp.fill('42.5');`,
      `      }`,
      `    }`,
      ``,
      `    // 3. Click primary action button`,
      `    const actionButton = page.locator('[data-mavi-id*="submit"], [data-mavi-id*="save"], [data-mavi-id*="button"]').first();`,
      `    if (await actionButton.isVisible()) {`,
      `      await actionButton.click();`,
      `      await page.waitForTimeout(1000);`,
      `    }`,
      ``,
      `    // 4. Verify no unhandled runtime crashes`,
      `    await expect(page.locator('text=Error:').first()).not.toBeVisible();`,
      `  });`,
      `});`,
      ``
    );

    return codeLines.join('\n');
  }
};
